Update PackageManagementControllerTest.java
IBM/sol003-lifecycle-driver pull request #28
Opened 2022-01-07 10:46 UTC by settipalli2F51

#issue/23

2022-01-07 14:01 UTC, swatij-ibm requested changes
1. Does this even build ? 
<img width="724" alt="Screenshot 2022-01-07 at 13 45 16" src="https://user-images.githubusercontent.com/55978914/148553116-e7a9b4d8-36dc-4775-84d9-fbdc05677735.png">
I don't see a 3.5.0 spring boot available https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent

2. I think we shouldn't be commenting out tests, I would prefer the tests to be handled and fixed. @hhellyer what do you suggest/think on this ?

3. This repo does not have any automated Jenkins etc to check the workability of the new build. Last I recall, when vulnerabilities were fixed, before merging the changes into develop, a test install was run using a locally built image with the required changes. 
Has an installation test with these changes been tested ? 
If not then probably this needs to be included and done before the merge to validate the newly built image of sol installs fine.

2022-01-07 14:30 UTC, clloydaccanto requested changes
I agree with the comments left by @swatij-ibm

2022-01-07 16:53 UTC, settipalli2F51 commented
Hi @swatij-ibm,@clloydaccanto .

As per your review comments ,fixed the issue and created the below PR .
https://github.com/IBM/sol003-lifecycle-driver/pull/28
Please find the low local build screen shot .
![image](https://user-images.githubusercontent.com/96560894/148577875-477bbbcc-06c8-4b00-8e13-582ef0521d15.png)

2022-01-07 17:21 UTC, swatij-ibm commented
Thanks for the update @settipalli2F51 .

As per the review comment provided above : https://github.com/IBM/sol003-lifecycle-driver/pull/28#pullrequestreview-846633636
> 2. I think we shouldn't be commenting out tests, I would prefer the tests to be handled and fixed. 

> 3. This repo does not have any automated Jenkins etc to check the workability of the new build. Last I recall, when vulnerabilities were fixed, before merging the changes into develop, a test install was run using a locally built image with the required changes.
    Has an installation test with these changes been tested ?
    If not then probably this needs to be included and done before the review and merge to validate the newly built image of sol installs fine.


Are you also looking to address the other requested changes ? 
I don't see the tests updated/fixed or any information about the installation test done for the new sol image ?

Please do address all the comments and also share details of the installation test being done, before sending out for re-review and merge.

2022-01-10 14:16 UTC, settipalli2F51 commented
Hi @swatij-ibm 

2.I think we shouldn't be commenting out tests, I would prefer the tests to be handled and fixed.
    ---> Now All Junit Test cases  are handled  by modifying the  Exception Handler .

3.This repo does not have any automated Jenkins etc to check the workability of the new build. Last I recall, when vulnerabilities were fixed, before merging the changes into develop, a test install was run using a locally built image with the required changes.
 -----> Done and Please find the latest installation  screen shot details .

![image](https://user-images.githubusercontent.com/96560894/148780263-07a1125d-853d-42db-8931-bcc11a07c6cb.png)

Has an installation test with these changes been tested ?
--- >Yes ,  Ran the all test cases with out fail . 

![image](https://user-images.githubusercontent.com/96560894/148780404-3894d793-b87a-47b8-81e1-cf5073936aa2.png)

2022-01-10 15:06 UTC, swatij-ibm approved these changes
Thanks for making the changes @settipalli2F51. 
LGTM 👍

2022-01-10 15:32 UTC, clloydaccanto requested changes

2022-01-10 15:32 UTC, clloydaccanto commented on pom.xml
> +            <version>30.0-jre</version>
can this version number please be moved into the properties section where other version are managed

2022-01-10 15:32 UTC, clloydaccanto commented on src/main/java/com/accantosystems/stratoss/vnfmdriver/web/etsi/ETSIExceptionHandlingControllerAdvice.java
> +        return new ResponseEntity<>("The requested response type was not acceptable", HttpStatus.NOT_ACCEPTABLE);
sorry but I don't think this is the right fix. We can't just change the response type from a ProblemDetails structure (as expected by the ETSI spec) to plain string response, especially as it won't contain the cause as it did previously. Also by not calling defaultHandle we no longer have any of the logging that went on in that method

2022-01-11 13:30 UTC, settipalli2F51 commented
we are planning to create new PR , So closing this PR .

2022-01-11 13:30 UTC, closed without merging