add kafka documentation
IBM/sol003-lifecycle-driver pull request #70
Opened 2022-06-08 09:00 UTC by settipalli2F51

Fix #4542 Updated kafka documentation file

2022-06-08 10:16 UTC, lokanalla requested changes
I had given wrong content earlier. Here is the right content:
-> By default kafka instance name is cp4na-o-events-kafka-bootstrap
For pre CP4NA v2.3, it must be iaf-system-kafka-bootstrap

2022-06-09 01:27 UTC, settipalli2F51 commented
Fix #72 and TNC[#4542] , Updated the Documentation changes related to kafka instance name for sol003-lifecycle-drivers

2022-06-09 01:47 UTC, settipalli2F51 commented
Documentation changes related to kafka instance name for sol003-lifecycle-drivers

2022-07-01 04:20 UTC, lokanalla requested changes

2022-07-01 04:20 UTC, lokanalla commented on docs/ConfiguringKafka.md
>        spring_kafka_bootstrap_servers: iaf-system-kafka-bootstrap:9092
By default, It will be cp4na-o-events-kafka-bootstrap

2022-07-01 04:20 UTC, lokanalla commented on docs/ConfiguringKafka.md
> +For CP4NA v2.3/v2.3+, it must be cp4na-o-events-kafka-bootstrap
What are you saying on line 20 and 22? Is it making any sense?

2022-08-09 12:05 UTC, closed without merging